import {clamp,readBuffer,readJSON} from './utils.js?v=1.1.0';
// Lightweight original WebGL renderer. No CDN or graphics-library dependency.
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
export function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[r+4]*b[c*4+1]+a[r+8]*b[c*4+2]+a[r+12]*b[c*4+3];return o;}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(eye,target){const norm=v=>{const n=Math.hypot(...v)||1;return v.map(a=>a/n);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
const VERT=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec3 aColor;uniform mat4 uProjection;uniform mat4 uView;uniform mat4 uModel;varying vec3 vNormal;varying vec3 vColor;varying vec3 vWorld;varying float vHeight;void main(){vec4 world=uModel*vec4(aPosition,1.);vNormal=mat3(uModel)*aNormal;vColor=aColor;vWorld=world.xyz;vHeight=aPosition.y;gl_Position=uProjection*uView*world;}`;
const FRAG=`precision mediump float;varying vec3 vNormal;varying vec3 vColor;varying vec3 vWorld;varying float vHeight;uniform float uAlpha;uniform float uEmission;uniform vec3 uCamera;void main(){vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;vec3 light=normalize(vec3(-0.45,0.9,0.65));float diffuse=max(dot(n,light),0.);float hemi=0.5+0.5*n.y;float back=max(dot(n,normalize(vec3(0.7,0.2,-0.8))),0.);float ao=mix(.79,1.,smoothstep(0.,.65,vHeight));vec3 col=vColor*(.42+diffuse*.58+hemi*.22+back*.12)*ao;vec3 view=normalize(uCamera-vWorld);float rim=pow(1.-max(dot(n,view),0.),3.)*.08;col+=rim*vec3(.6,.75,.68);col=mix(col,vColor,uEmission);gl_FragColor=vec4(col,uAlpha);}`;
export class HabitatViewer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true,xrCompatible:true});if(!this.gl)throw Error('WebGL is disabled. Enable hardware acceleration to view the 3D habitat.');this.active=false;this.autoRotate=true;this.pointers=new Map();this.count=0;this.yaw=.62;this.pitch=.37;this.distance=2.6;this.lastInteraction=0;this.xrSession=null;this.scale=1;this.cameraMode=false;this.screenShift=[0,0];this.dragMode='rotate';this.makeProgram();this.reticle=this.makeReticle();this.bind();this.resizeObserver=new ResizeObserver(()=>{if(!this.xrSession)this.resize();});this.resizeObserver.observe(canvas.parentElement);this.frame=0;this.loadTicket=0;}
 makeProgram(){const gl=this.gl,compile=(type,src)=>{const shader=gl.createShader(type);gl.shaderSource(shader,src);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader));return shader;},vs=compile(gl.VERTEX_SHADER,VERT),fs=compile(gl.FRAGMENT_SHADER,FRAG);this.program=gl.createProgram();gl.attachShader(this.program,vs);gl.attachShader(this.program,fs);gl.linkProgram(this.program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));gl.useProgram(this.program);this.attr={position:gl.getAttribLocation(this.program,'aPosition'),normal:gl.getAttribLocation(this.program,'aNormal'),color:gl.getAttribLocation(this.program,'aColor')};this.u={};for(const n of ['Projection','View','Model','Alpha','Emission','Camera'])this.u[n]=gl.getUniformLocation(this.program,'u'+n);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);}
 async load(id){const ticket=++this.loadTicket;this.id=id;const[meta,buffer]=await Promise.all([readJSON(`assets/models/${id}.json`),readBuffer(`assets/models/${id}.bin`)]);if(ticket!==this.loadTicket)return false;if(buffer.byteLength%36!==0||buffer.byteLength/36!==meta.vertices)throw Error('The model asset is incomplete. Extract the entire ZIP and retry.');const gl=this.gl;if(this.buffer)gl.deleteBuffer(this.buffer);this.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,buffer,gl.STATIC_DRAW);this.meta=meta;this.count=meta.vertices;this.reset();this.start();return true;}
 reset(){this.yaw=.64;this.pitch=.39;const rect=this.canvas.getBoundingClientRect(),aspect=Math.max(.35,rect.width/Math.max(1,rect.height));this.distance=Math.max(2.45,(this.meta?.height||1)*1.90,1.05/Math.tan(.315)/aspect);this.target=[0,(this.meta?.height||1)*.44,0];this.scale=1;this.screenShift=[0,0];this.lastInteraction=performance.now();this.render();}
 resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*dpr));this.canvas.height=Math.max(1,Math.round(r.height*dpr));if(this.count&&!this.xrSession)this.render();}
 bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{if(e.button!==0)return;c.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);this.lastInteraction=performance.now();this.pinch=null;});c.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;const old=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===2){const [a,b]=[...this.pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(this.pinch)this.distance=clamp(this.distance*this.pinch/d,1.0,9);this.pinch=d;}else if(this.cameraMode&&this.dragMode==='move'){const rect=c.getBoundingClientRect();this.screenShift[0]=clamp(this.screenShift[0]+(e.clientX-old[0])*2/rect.width,-.8,.8);this.screenShift[1]=clamp(this.screenShift[1]-(e.clientY-old[1])*2/rect.height,-.8,.8);}else{this.yaw-=(e.clientX-old[0])*.007;this.pitch=clamp(this.pitch+(e.clientY-old[1])*.006,-.06,1.35);}this.lastInteraction=performance.now();this.render();});for(const name of ['pointerup','pointercancel'])c.addEventListener(name,e=>{this.pointers.delete(e.pointerId);this.pinch=null;});c.addEventListener('wheel',e=>{e.preventDefault();this.distance=clamp(this.distance*Math.exp(clamp(e.deltaY*.001,-.18,.18)),1,9);this.lastInteraction=performance.now();this.render();},{passive:false});c.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')this.yaw-=.12;if(e.key==='ArrowRight')this.yaw+=.12;if(e.key==='ArrowUp')this.pitch=clamp(this.pitch+.08,-.06,1.35);if(e.key==='ArrowDown')this.pitch=clamp(this.pitch-.08,-.06,1.35);if(e.key==='+'||e.key==='=')this.distance=clamp(this.distance*.9,1,9);if(e.key==='-')this.distance=clamp(this.distance*1.1,1,9);this.lastInteraction=performance.now();this.render();});c.addEventListener('webglcontextlost',e=>{e.preventDefault();this.active=false;document.dispatchEvent(new CustomEvent('atlas-model-error',{detail:'The graphics context was interrupted. Close and reopen the 3D experience.'}));});}
 start(){this.active=true;cancelAnimationFrame(this.frame);this.resize();let prev=0;const loop=t=>{if(!this.active||this.xrSession)return;this.frame=requestAnimationFrame(loop);if(t-prev<30)return;const dt=prev?Math.min(.05,(t-prev)/1000):.03;prev=t;if(this.autoRotate&&performance.now()-this.lastInteraction>2500&&!matchMedia('(prefers-reduced-motion: reduce)').matches){this.yaw+=dt*.075;this.render();}};this.frame=requestAnimationFrame(loop);}
 stop(){this.active=false;cancelAnimationFrame(this.frame);}
 drawMesh(buffer,count,model,view,proj,camera,emission=0,alpha=1){const gl=this.gl;gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const[name,offset]of [['position',0],['normal',12],['color',24]]){const loc=this.attr[name];gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,36,offset);}gl.uniformMatrix4fv(this.u.Projection,false,proj);gl.uniformMatrix4fv(this.u.View,false,view);gl.uniformMatrix4fv(this.u.Model,false,model);gl.uniform3fv(this.u.Camera,camera);gl.uniform1f(this.u.Emission,emission);gl.uniform1f(this.u.Alpha,alpha);gl.drawArrays(gl.TRIANGLES,0,count);}
 render(){if(this.xrSession||!this.count||!this.canvas.width)return;const gl=this.gl,d=this.distance,p=this.pitch,eye=[Math.sin(this.yaw)*Math.cos(p)*d,this.target[1]+Math.sin(p)*d,Math.cos(this.yaw)*Math.cos(p)*d],view=lookAt(eye,this.target),proj=perspective(.63,this.canvas.width/this.canvas.height,.02,80);if(this.cameraMode){proj[8]=-this.screenShift[0];proj[9]=-this.screenShift[1];}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.BLEND);this.drawMesh(this.buffer,this.count,I(),view,proj,eye);}
 makeReticle(){const a=[];for(let i=0;i<48;i++){const t=i/48*Math.PI*2,u=(i+1)/48*Math.PI*2,p=[.12*Math.cos(t),.004,.12*Math.sin(t)],q=[.14*Math.cos(t),.004,.14*Math.sin(t)],r=[.14*Math.cos(u),.004,.14*Math.sin(u)],s=[.12*Math.cos(u),.004,.12*Math.sin(u)];for(const v of [p,q,r,p,r,s])a.push(...v,0,1,0,.72,.94,.59);}const b=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,b);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(a),this.gl.STATIC_DRAW);return{buffer:b,count:a.length/9};}
 async beginXR({overlay,onState,onEnd}){
 if(!navigator.xr||!isSecureContext)throw Error('Open this atlas on a compatible phone over HTTPS to enter floor AR.');
 let session;try{session=await navigator.xr.requestSession('immersive-ar',{requiredFeatures:['hit-test','dom-overlay'],optionalFeatures:['local-floor'],domOverlay:{root:overlay}});this.xrSession=session;this.stop();const gl=this.gl;await gl.makeXRCompatible();session.updateRenderState({baseLayer:new XRWebGLLayer(session,gl)});const space=await session.requestReferenceSpace('local'),viewerSpace=await session.requestReferenceSpace('viewer'),hitSource=await session.requestHitTestSource({space:viewerSpace});this.xrSpace=space;this.hitSource=hitSource;this.hitMatrix=null;this.placedMatrix=null;this.scale=1;overlay.hidden=false;
 const setGuide=(msg)=>{if(this.lastGuide!==msg){this.lastGuide=msg;onState?.(msg,!!this.hitMatrix,!!this.placedMatrix);}};
 session.addEventListener('select',()=>{if(!this.placedMatrix)this.placeXR();});
 session.addEventListener('end',()=>{hitSource.cancel();this.xrSession=null;this.hitMatrix=null;this.placedMatrix=null;overlay.hidden=true;document.documentElement.classList.remove('xr-active');gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.start();onEnd?.();},{once:true});
 overlay.onbeforexrselect=e=>{if(e.target.closest('button,input,label'))e.preventDefault();};document.documentElement.classList.add('xr-active');
 const frame=(time,f)=>{if(!this.xrSession)return;session.requestAnimationFrame(frame);const pose=f.getViewerPose(space);if(!pose)return;const hits=f.getHitTestResults(hitSource);this.hitMatrix=null;if(hits.length){const hit=hits[0].getPose(space);if(hit&&hit.transform.matrix[5]>.65)this.hitMatrix=new Float32Array(hit.transform.matrix);}setGuide(this.placedMatrix?'Walk around your ecosystem. Use Size to adjust it.':this.hitMatrix?'Floor found. Tap Place ecosystem.':'Move your phone slowly to find the floor.');const layer=session.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);for(const view of pose.views){const vp=layer.getViewport(view);gl.viewport(vp.x,vp.y,vp.width,vp.height);const cam=[view.transform.position.x,view.transform.position.y,view.transform.position.z];if(this.placedMatrix){const sc=I();sc[0]=sc[5]=sc[10]=this.scale;this.drawMesh(this.buffer,this.count,matMul(this.placedMatrix,sc),view.transform.inverse.matrix,view.projectionMatrix,cam);}else if(this.hitMatrix)this.drawMesh(this.reticle.buffer,this.reticle.count,this.hitMatrix,view.transform.inverse.matrix,view.projectionMatrix,cam,1);}};session.requestAnimationFrame(frame);
 }catch(e){this.xrSession=null;if(session)await session.end().catch(()=>{});overlay.hidden=true;document.documentElement.classList.remove('xr-active');this.start();throw e;}
 }
 placeXR(){if(this.hitMatrix){this.placedMatrix=new Float32Array(this.hitMatrix);this.lastGuide='';return true;}return false;}
 repositionXR(){this.placedMatrix=null;this.lastGuide='';}
 async endXR(){if(this.xrSession)await this.xrSession.end();}
 screenshot(){this.render();return this.canvas.toDataURL('image/png');}
 destroy(){this.stop();this.loadTicket++;this.resizeObserver.disconnect();if(this.buffer)this.gl.deleteBuffer(this.buffer);if(this.reticle)this.gl.deleteBuffer(this.reticle.buffer);this.gl.deleteProgram(this.program);}
}
