import {clamp,loadImage,netFetch,debounce,esc} from './utils.js';
import {CIRCUMFERENCE} from './map.js';
// Minimal, bounded Mapbox Vector Tile decoder; geometry is from the provider, not fabricated.
class PBFReader {
 constructor(bytes){this.b=bytes;this.i=0;this.end=bytes.length;}
 varint(){let n=0,shift=0;while(this.i<this.end&&shift<56){const v=this.b[this.i++];n+=(v&127)*2**shift;if(!(v&128))return n;shift+=7;}throw Error('Invalid PBF varint');}
 bytes(){const n=this.varint(),end=this.i+n;if(end>this.end)throw Error('Truncated PBF');const b=this.b.subarray(this.i,end);this.i=end;return b;}
 skip(w){if(w===0)this.varint();else if(w===1)this.i+=8;else if(w===2){const n=this.varint();this.i+=n;}else if(w===5)this.i+=4;else throw Error('Unsupported PBF wire type');if(this.i>this.end)throw Error('Truncated PBF field');}
}
export function decodeMVT(buffer){if(buffer.byteLength>16*1024*1024)throw Error('Vector tile too large');const p=new PBFReader(new Uint8Array(buffer)),layers=[];while(p.i<p.end){const t=p.varint();if((t>>3)===3&&(t&7)===2)layers.push(parseLayer(p.bytes()));else p.skip(t&7);}return layers;}
function parseLayer(bytes){const p=new PBFReader(bytes),features=[];let extent=4096,name='';while(p.i<p.end){const t=p.varint(),f=t>>3,w=t&7;if(f===1&&w===2)name=new TextDecoder().decode(p.bytes());else if(f===2&&w===2)features.push(parseFeature(p.bytes()));else if(f===5&&w===0)extent=p.varint();else p.skip(w);}if(!(extent>0&&extent<1e7))throw Error('Invalid tile extent');return{name,extent,features};}
function parseFeature(bytes){const p=new PBFReader(bytes);let type=0,g=[];while(p.i<p.end){const t=p.varint(),f=t>>3,w=t&7;if(f===3&&w===0)type=p.varint();else if(f===4&&w===2){const q=new PBFReader(p.bytes());while(q.i<q.end)g.push(q.varint());}else p.skip(w);}let x=0,y=0,i=0,path=[],paths=[];const unzig=n=>n%2?-(n+1)/2:n/2;while(i<g.length){const cmd=g[i++],id=cmd&7,count=Math.floor(cmd/8);if(count>1e6)throw Error('Invalid tile command');if(id===1||id===2){for(let k=0;k<count;k++){if(i+1>=g.length)throw Error('Truncated geometry');x+=unzig(g[i++]);y+=unzig(g[i++]);if(id===1&&path.length){paths.push(path);path=[];}path.push([x,y]);}}else if(id===7){if(path.length)path.push([...path[0]]);}else throw Error('Invalid geometry command');}if(path.length)paths.push(path);return{type,paths};}
function proxyURL(url){return document.querySelector('meta[name="atlas-proxy"]')?.content==='enabled'?'/api/remote?url='+encodeURIComponent(url):url;}
export class LayerManager{
 constructor(map,sites,onStatus){this.map=map;this.sites=sites;this.onStatus=onStatus;this.active=new Set();this.opacity=.75;this.date='2024-11-30';this.cache=new Map();this.queue=[];this.inflight=0;this.visible=[];this.version=0;this.updateLater=debounce(()=>this.update(),320);map.on('moveend',()=>this.updateLater());map.on('resize',()=>this.updateLater());map.painter=c=>this.paint(c);}
 toggle(id,on){if(on)this.active.add(id);else this.active.delete(id);this.update();}
 clear(){this.active.clear();this.queue=[];this.visible=[];this.map.requestDraw();this.report();}
 setDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;this.date=date;this.update();}
 retry(){for(const [k,v]of this.cache)if(v.error)this.cache.delete(k);this.update();}
 update(){const map=this.map;if(!map.width)return;this.version++;const visible=[];const b=map.bounds();for(const id of this.active){const e=this.sites.find(e=>e.id===id),z=Math.min(14,Math.max(0,Math.floor(map.zoom-1))),n=2**z;for(let x=Math.floor(b[0]*n);x<=Math.floor(b[2]*n);x++){for(let y=Math.max(0,Math.floor(b[1]*n));y<=Math.min(n-1,Math.floor(b[3]*n));y++){const xx=((x%n)+n)%n,key=`${id}/${z}/${xx}/${y}/${id==='plankton'?this.date:'static'}`;let item=this.cache.get(key);if(!item){item={key,id,z,x:xx,y,n,status:'queued',e,date:this.date};this.cache.set(key,item);this.queue.push(item);}if(item.status==='queued'&&!this.queue.includes(item))this.queue.push(item);visible.push({item,displayX:x});}}}this.visible=visible;this.queue=this.queue.filter(t=>this.active.has(t.id));this.pump();this.map.requestDraw();this.report();this.trim();}
 trim(){if(this.cache.size<240)return;const keep=new Set(this.visible.map(t=>t.item.key));for(const[k,v]of this.cache){if(!keep.has(k)&&v.status!=='loading')this.cache.delete(k);if(this.cache.size<=160)break;}}
 pump(){while(this.inflight<5&&this.queue.length){const item=this.queue.shift();if(item.status!=='queued')continue;item.status='loading';this.inflight++;this.fetchTile(item).then(()=>{item.status='ready';}).catch(e=>{item.status='error';item.error=String(e.message||e);}).finally(()=>{this.inflight--;this.map.requestDraw();this.report();this.pump();});}}
 async fetchTile(t){const {e,z,x,y,n}=t,l=e.layer;
 if(l.type==='mvt'){const r=await netFetch(proxyURL(`${l.url}/tile/${z}/${y}/${x}.pbf`));t.features=decodeMVT(await r.arrayBuffer());return;}
 const xmin=(x/n-.5)*CIRCUMFERENCE,xmax=((x+1)/n-.5)*CIRCUMFERENCE,ymax=(.5-y/n)*CIRCUMFERENCE,ymin=(.5-(y+1)/n)*CIRCUMFERENCE;
 let url;
 if(l.type==='arcgis'){const params=new URLSearchParams({bbox:[xmin,ymin,xmax,ymax].join(','),bboxSR:'3857',imageSR:'3857',size:'512,512',dpi:'96',format:'png32',transparent:'true',layers:'show:'+l.layers,f:'image'});url=l.url+'/export?'+params;}
 else{const params=new URLSearchParams({service:'WMS',version:'1.1.1',request:'GetMap',layers:l.wmsLayer,styles:'',format:'image/png',transparent:'TRUE',srs:'EPSG:3857',bbox:[xmin,ymin,xmax,ymax].join(','),width:'512',height:'512'});if(l.type==='wms')params.set('time',t.date);url=l.url+(l.url.includes('?')?'&':'?')+params;}
 const im=await loadImage(proxyURL(url),{cors:l.type==='worldcover',timeout:20000});
 if(l.type==='worldcover'){
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const c=canvas.getContext('2d',{willReadFrequently:true});c.drawImage(im,0,0,512,512);const data=c.getImageData(0,0,512,512),p=data.data;const rgb=e.color.match(/\w\w/g).map(s=>parseInt(s,16));for(let i=0;i<p.length;i+=4){const tree=p[i]<45&&p[i+1]>=72&&p[i+1]<=132&&p[i+2]<48;p[i]=rgb[0];p[i+1]=rgb[1];p[i+2]=rgb[2];p[i+3]=tree?235:0;}c.putImageData(data,0,0);t.image=canvas;
 }else if(l.type==='arcgis'){
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const c=canvas.getContext('2d');c.drawImage(im,0,0,512,512);c.globalCompositeOperation='source-in';c.fillStyle=e.color;c.fillRect(0,0,512,512);t.image=canvas;
 }else t.image=im;
 t.requestURL=url;
 }
 paint(c){const map=this.map;for(const{item:t,displayX}of this.visible){if(t.status!=='ready'||!this.active.has(t.id))continue;const n=t.n,s=map.scale/n,p=map.normalPoint([displayX/n,t.y/n],false);c.save();c.globalAlpha=this.opacity;c.beginPath();c.rect(p[0],p[1],s+.5,s+.5);c.clip();if(t.id==='forest'){const a=map.point([0,23.44])[1],b=map.point([0,-23.44])[1];c.beginPath();c.rect(0,a,map.width,b-a);c.clip();}if(t.image)c.drawImage(t.image,p[0],p[1],s+.5,s+.5);
 if(t.features){c.fillStyle=t.e.color;c.strokeStyle=t.e.color;c.lineWidth=1.25;for(const layer of t.features){const f=s/layer.extent;for(const feature of layer.features){if(feature.type===1){for(const path of feature.paths)for(const q of path){c.beginPath();c.arc(p[0]+q[0]*f,p[1]+q[1]*f,2.3,0,Math.PI*2);c.fill();}}else{c.beginPath();for(const path of feature.paths){for(let i=0;i<path.length;i++){const q=[p[0]+path[i][0]*f,p[1]+path[i][1]*f];i?c.lineTo(...q):c.moveTo(...q);}if(feature.type===3)c.closePath();}if(feature.type===3)c.fill('evenodd');c.stroke();}}}}
 c.restore();}}
 report(){if(!this.active.size){this.onStatus({visible:false});return;}const keys=new Set(),items=[];for(const{item}of this.visible){if(!keys.has(item.key)){keys.add(item.key);items.push(item);}}const ready=items.filter(t=>t.status==='ready').length,errors=items.filter(t=>t.status==='error').length,pending=items.length-ready-errors;const names=[...this.active].map(id=>this.sites.find(e=>e.id===id).short);let text;if(pending)text=`Loading ${names.join(' + ')} · ${ready}/${items.length} map tiles`;else if(errors)text=ready?`${ready} tiles loaded; ${errors} unavailable. Refresh to retry.`:`${names.join(' + ')} data service is not reachable. Refresh to retry.`;else text=`${names.join(' + ')} · ${ready} map tiles loaded`;
 const methods=[...this.active].map(id=>{const l=this.sites.find(e=>e.id===id).layer;return l.method;});this.onStatus({visible:true,text,detail:methods.join(' · ')+(this.active.has('plankton')?' · '+this.date:''),errors,ready,pending,tiles:items.length});}
}
export function validateGeoJSON(data){let count=0;const walk=g=>{if(!g||typeof g!=='object')throw Error('Expected a GeoJSON object.');if(g.type==='FeatureCollection'){if(!Array.isArray(g.features)||g.features.length>10000)throw Error('Use 10,000 features or fewer.');g.features.forEach(walk);}else if(g.type==='Feature'){count++;if(g.geometry!==null)walk(g.geometry);}else if(g.type==='GeometryCollection'){if(!Array.isArray(g.geometries))throw Error('Invalid geometry collection.');g.geometries.forEach(walk);}else if(['Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon'].includes(g.type)){const check=(a,depth=0)=>{if(!Array.isArray(a)||depth>6)throw Error('Invalid coordinates.');if(typeof a[0]==='number'){if(a.length<2||!a.every(Number.isFinite)||Math.abs(a[0])>180||Math.abs(a[1])>90)throw Error('Coordinates must be WGS 84 longitude/latitude.');if(++count>500000)throw Error('Use a simplified GeoJSON under 500,000 coordinate pairs.');}else a.forEach(b=>check(b,depth+1));};check(g.coordinates);}else throw Error('Unsupported GeoJSON geometry.');};walk(data);return data;}
