import {clamp,readJSON,loadImage,debounce} from './utils.js';
export const EARTH=6378137;
export const CIRCUMFERENCE=2*Math.PI*EARTH;
export const project=([lng,lat])=>[(lng+180)/360,(1-Math.asinh(Math.tan(clamp(lat,-85.05112878,85.05112878)*Math.PI/180))/Math.PI)/2];
export const unproject=([x,y])=>[x*360-180,Math.atan(Math.sinh(Math.PI*(1-2*y)))*180/Math.PI];
export const haversine=(a,b)=>{const r=Math.PI/180,dlat=(b[1]-a[1])*r,dlon=(b[0]-a[0])*r,h=Math.sin(dlat/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(dlon/2)**2;return 6371.0088*2*Math.atan2(Math.sqrt(clamp(h,0,1)),Math.sqrt(clamp(1-h,0,1)));};
export function greatCircle(a,b,steps=64){const R=Math.PI/180,toV=([l,t])=>[Math.cos(t*R)*Math.cos(l*R),Math.cos(t*R)*Math.sin(l*R),Math.sin(t*R)];const v=toV(a),w=toV(b),d=Math.acos(clamp(v.reduce((s,x,i)=>s+x*w[i],0),-1,1));if(d<1e-6||Math.abs(Math.sin(d))<1e-6)return[a,b];return Array.from({length:steps+1},(_,i)=>{const f=Math.sin((1-i/steps)*d)/Math.sin(d),g=Math.sin(i/steps*d)/Math.sin(d),p=v.map((x,j)=>x*f+w[j]*g);return[Math.atan2(p[1],p[0])/R,Math.atan2(p[2],Math.hypot(p[0],p[1]))/R];});}
const bgLabels=[[-107,51,'NORTH AMERICA'],[-62,-8,'SOUTH AMERICA'],[21,5,'AFRICA'],[17,52,'EUROPE'],[89,47,'ASIA'],[134,-24,'AUSTRALIA'],[-35,18,'A T L A N T I C'],[78,-17,'I N D I A N  O C E A N'],[-142,0,'P A C I F I C  O C E A N'],[176,4,'P A C I F I C']];
export class AtlasMap {
 constructor(canvas,markers,sites){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.markerEl=markers;this.sites=sites;this.center=project([20,12]);this.zoom=1.8;this.padding={left:380,right:0,top:0,bottom:0};this.listeners=new Map();this.tiles=new Map();this.pointers=new Map();this.base='atlas';this.measurePoints=[];this.measuring=false;this.userPosition=null;this.imported=null;this.rings=[];this.pendingDraw=false;this.painter=null;this.animation=0;this.loadWorld();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.bind();this.resize();}
 on(type,fn){if(!this.listeners.has(type))this.listeners.set(type,[]);this.listeners.get(type).push(fn);return()=>this.listeners.set(type,this.listeners.get(type).filter(f=>f!==fn));}
 emit(type,value){for(const f of this.listeners.get(type)||[])f(value);}
 async loadWorld(){try{const geo=await readJSON('assets/geo/world.json');this.world=geo;for(const f of geo.features){const poly=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const rings of poly){const projected=rings.map(r=>{let prev;return r.map(pt=>{const p=project(pt);if(prev!==undefined){while(p[0]-prev>.5)p[0]-=1;while(p[0]-prev<-.5)p[0]+=1;}prev=p[0];return p;});});this.rings.push(projected);}}this.draw();this.emit('ready',true);}catch(e){this.emit('error',e.message);}}
 resize(){const r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*this.dpr));this.canvas.height=Math.max(1,Math.round(r.height*this.dpr));this.requestDraw();this.emit('resize');}
 get scale(){return 256*2**this.zoom;}
 get anchor(){return[(this.width+this.padding.left-this.padding.right)/2,(this.height+this.padding.top-this.padding.bottom)/2];}
 setPadding(p){this.padding={left:0,right:0,top:0,bottom:0,...p};this.requestDraw();}
 getView(){return{lng:unproject(this.center)[0],lat:unproject(this.center)[1],zoom:this.zoom};}
 point(ll){return this.normalPoint(project(ll));}
 normalPoint(p,wrap=true){let dx=p[0]-this.center[0];if(wrap)dx-=Math.round(dx);const a=this.anchor;return[a[0]+dx*this.scale,a[1]+(p[1]-this.center[1])*this.scale];}
 coord(x,y){const a=this.anchor;const p=unproject([this.center[0]+(x-a[0])/this.scale,this.center[1]+(y-a[1])/this.scale]);return[((p[0]+180)%360+360)%360-180,p[1]];}
 bounds(){const a=this.anchor,s=this.scale;return[this.center[0]-a[0]/s,this.center[1]-(a[1])/s,this.center[0]+(this.width-a[0])/s,this.center[1]+(this.height-a[1])/s];}
 home(){const avail=this.width-this.padding.left-this.padding.right;const z=clamp(Math.log2(Math.max(260,avail-70)/256/1.0),.25,2.35);this.flyTo([20,13],z);}
 flyTo(ll,z=5){cancelAnimationFrame(this.animation);const start=[...this.center],end=project(ll);end[0]+=Math.round(start[0]-end[0]);const sz=this.zoom,t0=performance.now(),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:650;this.emit('movestart');const step=t=>{const f=duration?clamp((t-t0)/duration,0,1):1,k=1-(1-f)**3;this.center=[start[0]+(end[0]-start[0])*k,start[1]+(end[1]-start[1])*k];this.zoom=sz+(clamp(z,.1,17)-sz)*k;this.requestDraw();this.emit('move',this.getView());if(f<1)this.animation=requestAnimationFrame(step);else this.endMove();};this.animation=requestAnimationFrame(step);}
 endMove(){this.center[0]=((this.center[0]%1)+1)%1;this.center[1]=clamp(this.center[1],.005,.995);this.emit('moveend',this.getView());this.requestDraw();}
 zoomAt(delta,x=this.anchor[0],y=this.anchor[1]){cancelAnimationFrame(this.animation);const a=this.anchor,before=this.scale;const nx=this.center[0]+(x-a[0])/before,ny=this.center[1]+(y-a[1])/before;this.zoom=clamp(this.zoom+delta,.1,17);this.center=[nx-(x-a[0])/this.scale,clamp(ny-(y-a[1])/this.scale,.005,.995)];this.requestDraw();this.emit('move',this.getView());this.finishWheel();}
 setBase(b){this.base=b;this.baseLoaded=0;this.baseErrors=0;if(b==='satellite')this.emit('basestatus','Loading satellite imagery…');this.requestDraw();}
 setMeasure(b){this.measuring=b;if(!b)this.measurePoints=[];this.requestDraw();}
 requestDraw(){if(!this.pendingDraw){this.pendingDraw=true;requestAnimationFrame(()=>{this.pendingDraw=false;this.draw();});}}
 bind(){this.finishWheel=debounce(()=>this.endMove(),220);const c=this.canvas;
 c.addEventListener('wheel',e=>{e.preventDefault();const r=c.getBoundingClientRect();this.zoomAt(clamp(-e.deltaY*.002,-.4,.4),e.clientX-r.left,e.clientY-r.top);},{passive:false});
 c.addEventListener('dblclick',e=>{if(this.measuring)return;const r=c.getBoundingClientRect();this.zoomAt(.8,e.clientX-r.left,e.clientY-r.top);});
 c.addEventListener('pointerdown',e=>{if(e.button!==0)return;cancelAnimationFrame(this.animation);c.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);this.dragStart=[e.clientX,e.clientY];this.moved=false;this.pinch=null;this.emit('movestart');});
 c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();this.emit('pointer',this.coord(e.clientX-r.left,e.clientY-r.top));if(!this.pointers.has(e.pointerId))return;const old=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===2){const [a,b]=[...this.pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]),mid=[(a[0]+b[0])/2-r.left,(a[1]+b[1])/2-r.top];if(this.pinch)this.zoomAt(Math.log2(d/this.pinch),...mid);this.pinch=d;this.moved=true;}else{const dx=e.clientX-old[0],dy=e.clientY-old[1];if(Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>4)this.moved=true;this.center[0]-=dx/this.scale;this.center[1]=clamp(this.center[1]-dy/this.scale,.005,.995);this.requestDraw();this.emit('move',this.getView());}});
 const up=e=>{const was=this.pointers.has(e.pointerId);this.pointers.delete(e.pointerId);this.pinch=null;if(was&&!this.moved&&this.measuring){const r=c.getBoundingClientRect();if(this.measurePoints.length===2)this.measurePoints=[];this.measurePoints.push(this.coord(e.clientX-r.left,e.clientY-r.top));this.emit('measure',this.measurePoints);this.requestDraw();}if(!this.pointers.size)this.endMove();};c.addEventListener('pointerup',up);c.addEventListener('pointercancel',up);
 c.addEventListener('keydown',e=>{if(['+','=','-','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')this.zoomAt(.5);if(e.key==='-')this.zoomAt(-.5);const pan=65/this.scale;if(e.key==='ArrowUp')this.center[1]-=pan;if(e.key==='ArrowDown')this.center[1]+=pan;if(e.key==='ArrowLeft')this.center[0]-=pan;if(e.key==='ArrowRight')this.center[0]+=pan;if(e.key.startsWith('Arrow'))this.endMove();});}
 draw(){if(!this.width)return;const c=this.ctx,s=this.scale,[ax,ay]=this.anchor;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.width,this.height);
 const grad=c.createRadialGradient(this.width*.68,this.height*.52,25,this.width*.57,this.height*.53,this.width*.8);grad.addColorStop(0,'#12292e');grad.addColorStop(.47,'#102229');grad.addColorStop(1,'#0b181f');c.fillStyle=grad;c.fillRect(0,0,this.width,this.height);
 c.save();c.strokeStyle='#708e8b10';c.lineWidth=.6;for(let lon=-180;lon<180;lon+=30){let x=this.point([lon,0])[0];c.beginPath();c.moveTo(x,0);c.lineTo(x,this.height);c.stroke();}for(let lat=-60;lat<=75;lat+=15){let y=this.point([0,lat])[1];c.beginPath();c.moveTo(0,y);c.lineTo(this.width,y);c.stroke();}c.restore();
 this.paintWorld(c);
 if(this.base==='satellite')this.paintTiles(c);
 this.painter?.(c);
 if(this.imported)this.drawGeoJSON(this.imported,'#b7adfa',.42);
 this.paintLabels(c);
 if(this.measurePoints.length){c.save();c.strokeStyle='#d7e5ba';c.lineWidth=2;c.setLineDash([5,4]);if(this.measurePoints.length===2){const pts=greatCircle(...this.measurePoints).map(p=>this.point(p));c.beginPath();for(let i=0;i<pts.length;i++){if(i&&Math.abs(pts[i][0]-pts[i-1][0])<this.width*.8)c.lineTo(...pts[i]);else c.moveTo(...pts[i]);}c.stroke();}c.setLineDash([]);for(const pt of this.measurePoints){const p=this.point(pt);c.fillStyle='#b4db9b';c.beginPath();c.arc(...p,5,0,Math.PI*2);c.fill();c.strokeStyle='#101b1b';c.stroke();}c.restore();}
 for(const e of this.markerEl.querySelectorAll('.marker')){const site=this.sites.find(s=>s.id===e.dataset.id);const p=this.point([site.lng,site.lat]);if(site.id==='saltmarsh'&&this.zoom<3.3){c.save();c.strokeStyle=site.color+'99';c.lineWidth=1;c.setLineDash([2,3]);c.beginPath();c.moveTo(...p);p[0]-=50;p[1]-=18;c.lineTo(...p);c.stroke();c.restore();}e.style.left=p[0]+'px';e.style.top=p[1]+'px';e.style.visibility=(p[0]<-100||p[0]>this.width+100||p[1]<-20||p[1]>this.height+80)?'hidden':'visible';}
 if(this.userPosition){const p=this.point(this.userPosition);c.save();c.fillStyle='#82bdd62a';c.beginPath();c.arc(...p,18,0,Math.PI*2);c.fill();c.fillStyle='#81c8e4';c.strokeStyle='white';c.lineWidth=2;c.beginPath();c.arc(...p,5,0,Math.PI*2);c.fill();c.stroke();c.restore();}
 const centerLat=unproject(this.center)[1],kmPerPixel=CIRCUMFERENCE*Math.cos(centerLat*Math.PI/180)/s/1000;this.emit('scale',kmPerPixel*80);
 }
 paintWorld(c){c.fillStyle=this.base==='satellite'?'#273e37':'#263937';c.strokeStyle=this.base==='satellite'?'#60766825':'#61766a29';c.lineWidth=.6;
 for(const rings of this.rings){for(let wrap=-1;wrap<=1;wrap++){let xs=rings[0].map(p=>p[0]);const avg=(Math.min(...xs)+Math.max(...xs))/2;const shift=Math.round(this.center[0]-avg)+wrap;c.beginPath();let visible=false;for(const ring of rings){ring.forEach((p,i)=>{const q=this.normalPoint([p[0]+shift,p[1]],false);if(q[0]>-this.scale*.2&&q[0]<this.width+this.scale*.2)visible=true;i?c.lineTo(...q):c.moveTo(...q);});c.closePath();}if(visible){c.fill('evenodd');c.stroke();}}}
 // Equator sits above land but below data; it is a coordinate guide, not a habitat layer.
 const equator=this.point([0,0])[1];c.save();c.strokeStyle='#8ea79914';c.setLineDash([3,7]);c.beginPath();c.moveTo(0,equator);c.lineTo(this.width,equator);c.stroke();c.restore();}
 paintLabels(c){if(this.base==='satellite')return;c.save();c.font=`${this.width<650?7:9}px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif`;c.textAlign='center';for(const [lng,lat,name]of bgLabels){const [x,y]=this.point([lng,lat]);if(x<0||x>this.width||y<0||y>this.height)continue;c.fillStyle=name.includes('OCEAN')||name.includes('A T L')?'#54787c80':'#829d8970';c.fillText(name,x,y);}if(this.zoom>4){c.font='10px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';c.fillStyle='#9aa99790';for(const f of this.world?.features||[]){if(!f.geometry)continue;const rings=f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flat();const pts=rings.flat();let xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const lng=(Math.min(...xs)+Math.max(...xs))/2,lat=(Math.min(...ys)+Math.max(...ys))/2;const [x,y]=this.point([lng,lat]);if(x>0&&x<this.width&&y>0&&y<this.height)c.fillText(f.properties.name,x,y);}}c.restore();}
 paintTiles(c){const z=Math.min(17,Math.max(0,Math.floor(this.zoom))),n=2**z,b=this.bounds(),tSize=this.scale/n;let minX=Math.floor(b[0]*n),maxX=Math.floor(b[2]*n),minY=Math.max(0,Math.floor(b[1]*n)),maxY=Math.min(n-1,Math.floor(b[3]*n));for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++){const xx=((x%n)+n)%n,key=`${z}/${y}/${xx}`;let tile=this.tiles.get(key);if(!tile){tile={loading:true};this.tiles.set(key,tile);loadImage(`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${key}`).then(im=>{tile.image=im;tile.loading=false;this.baseLoaded++;if(this.baseLoaded===1)this.emit('basestatus','Satellite imagery · Esri, Maxar, Earthstar Geographics & contributors');this.requestDraw();}).catch(()=>{tile.error=true;tile.loading=false;this.baseErrors++;if(!this.baseLoaded)this.emit('basestatus','Satellite service not reachable. The bundled atlas remains available.');});}if(tile.image){const p=this.normalPoint([x/n,y/n],false);c.drawImage(tile.image,p[0],p[1],tSize+1,tSize+1);}}if(this.tiles.size>220){for(const [key,value]of this.tiles){if(!key.startsWith(z+'/'))this.tiles.delete(key);if(this.tiles.size<=160)break;}}}
 drawGeoJSON(fc,color='#b4db9b',alpha=.6){const c=this.ctx;c.save();c.globalAlpha=alpha;c.fillStyle=color;c.strokeStyle=color;c.lineWidth=1.1;const drawGeom=g=>{if(!g)return;let polygons=[];if(g.type==='Polygon')polygons=[g.coordinates];if(g.type==='MultiPolygon')polygons=g.coordinates;if(polygons.length){for(const poly of polygons){c.beginPath();for(const ring of poly){let prior;ring.forEach((v,i)=>{const p=this.point(v);if(prior&&Math.abs(p[0]-prior[0])>this.scale/2){p[0]+=p[0]<prior[0]?this.scale:-this.scale;}i?c.lineTo(...p):c.moveTo(...p);prior=p;});c.closePath();}c.fill('evenodd');c.stroke();}}else if(g.type==='Point'||g.type==='MultiPoint'){for(const v of g.type==='Point'?[g.coordinates]:g.coordinates){const p=this.point(v);c.beginPath();c.arc(...p,3,0,Math.PI*2);c.fill();}}else if(g.type==='LineString'||g.type==='MultiLineString'){for(const line of g.type==='LineString'?[g.coordinates]:g.coordinates){c.beginPath();line.forEach((v,i)=>{const p=this.point(v);i?c.lineTo(...p):c.moveTo(...p);});c.stroke();}}else if(g.type==='GeometryCollection')g.geometries.forEach(drawGeom);};if(fc.type==='FeatureCollection')fc.features.forEach(f=>drawGeom(f.geometry));else if(fc.type==='Feature')drawGeom(fc.geometry);else drawGeom(fc);c.restore();}
 destroy(){this.resizeObserver.disconnect();cancelAnimationFrame(this.animation);}
}
